import type { Metadata } from "next";
import { Urbanist, Inter } from "next/font/google";
import "./globals.css";

import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { cn } from "@/lib/utils";

import { Analytics } from "@vercel/analytics/next"
import { SpeedInsights } from '@vercel/speed-insights/next';


const urbanist = Urbanist({
  subsets: ['latin'],
  variable: '--font-urbanist'
})

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter'
})


export const metadata: Metadata = {
  title: "AutoKraft",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full antialiased",
        urbanist.variable,
        inter.variable
      )}
    >

      <body className="min-h-full flex flex-col bg-[#101926] text-[#f5f5f5]">
        <Analytics />
        <SpeedInsights />
        <Navbar />
        <div>{children}</div>
        <Footer />
      </body>
    </html>
  );
}
